#!/bin/sh
# File generated by ocamlbuild

cd /Users/neco/Desktop/Et\ Al/OCaml

rm -f GabProj.cmi
rm -f GabProj.cmo
rm -f KnightMatrix.cmi
rm -f KnightMatrix.cmo
rm -f Knights.cmi
rm -f Knights.cmo
rm -f KnightsC.cmi
rm -f KnightsC.cmo
rm -f KnightsFinal.cmi
rm -f KnightsFinal.cmo
rm -f KnightsFinal.cmx
rm -f KnightsFinal.o
rm -f ProCar.cmx
rm -f ProCar.o
rm -f Procar.cmi
rm -f Procar.cmo
rm -f ProjA.cmi
rm -f ProjA.cmo
rm -f ProjA.cmx
rm -f ProjA.o
rm -f ProjB.cmi
rm -f ProjB.cmo
rm -f ProjB.cmx
rm -f ProjB.o
rm -f ProjC.cmi
rm -f ProjC.cmo
rm -f hello.cmi
rm -f hello.cmo
rm -f leapyear.cmi
rm -f leapyear.cmo
# Also clean the script itself
rm -f /Users/neco/Desktop/OCaml/_build/sanitize.sh
